### ISSUE TITLE
Paper?

### ISSUE THREAD

**Issue by free001style** [lipperr/score_based_change_point_detection#1]
Hi, A Markovich! Nice work👏 But where I can find this paper? Thanks for answer.

**Comment by lipperr** [comment]
Hi Ilya! I'm sorry it took me a long time to respond, and thank you for your interest in my work! The repository has been updated with a link to an arXiv preprint publication. If you have any questions about our paper or experiments, please feel free to contact me at a.al.markovich@gmail.com.

**Comment by free001style** [comment]
Thanks again for your reply. Your paper is amazing! I'm looking forward your future success. 
So I'm closing this issue.
